"""
This type stub file was generated by pyright.
"""

import urllib.request
import zipfile

"""Centralized I/O security sentinel for NLTK."""
ENFORCE = ...
_ALLOWED_ROOTS_CACHE = ...
_LAST_DATA_PATHS = ...
def validate_path(path_input, context=..., required_root=...):
    """
    Ensures file access is restricted to allowed data directories.

    :param path_input: The path to validate.
    :param context: Diagnostic context for warnings/errors.
    :param required_root: If provided, enforces that the path is strictly
                          within this specific directory (scoped sandbox).
    """
    ...

def validate_zip_archive(zip_obj_or_path, target_root, specific_member=..., context=...): # -> None:
    """Enhanced Zip-Slip protection using Pathlib for cross-platform safety."""
    ...

def validate_network_url(url_input, context=...):
    """Hardened URL validation with SSRF protection."""
    ...

class _ValidatingRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Ensures that every step of a redirect chain is re-validated against SSRF."""
    def redirect_request(self, req, fp, code, msg, headers, newurl): # -> Request | None:
        ...
    


def urlopen(url, *args, **kwargs): # -> _UrlopenRet:
    """Secure wrapper for urllib.request.urlopen with redirect validation."""
    ...

def open(file, mode=..., **kwargs): # -> IO[Any]:
    """Secure wrapper for builtins.open."""
    ...

class ZipFile(zipfile.ZipFile):
    """Secure wrapper for zipfile.ZipFile."""
    def __init__(self, file, *args, **kwargs) -> None:
        ...
    
    def extract(self, member, path=..., pwd=...): # -> str:
        ...
    
    def extractall(self, path=..., members=..., pwd=...): # -> None:
        ...
    


__all__ = ["validate_path", "validate_network_url", "validate_zip_archive", "open", "urlopen", "ZipFile", "ENFORCE"]
