"""
This type stub file was generated by pyright.
"""

import pickle
from typing import Any, BinaryIO

"""
Helpers for safer and/or more explicit pickle usage in NLTK.

- RestrictedUnpickler: blocks unpickling of *any* globals (classes/functions).
  Intended for loading NLTK data packages where we control the serialization.
- WarningUnpickler: emits a security warning before unpickling (does not make
  unpickling safe).
"""
PICKLE_WARNING = ...
class RestrictedUnpickler(pickle.Unpickler):
    """
    Unpickler that prevents any class or function from being used during loading.
    """
    def find_class(self, module: str, name: str) -> Any:
        ...
    


class WarningUnpickler(pickle.Unpickler):
    """Unpickler that emits PICKLE_WARNING once per instance."""
    def __init__(self, file: BinaryIO, *, context: str | None = ..., **kwargs: Any) -> None:
        ...
    
    def load(self) -> Any:
        ...
    


def pickle_load(file: BinaryIO, *, context: str | None = ..., restricted: bool = ...) -> Any:
    """
    Convenience wrapper similar to pickle.load(file).

    - If restricted=True, uses RestrictedUnpickler (no warning by default).
    - If restricted=False, uses WarningUnpickler and emits a warning.
    """
    ...

